# Generated by Django 4.0.5 on 2022-07-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescripcion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cantidad',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
